blog/urls.py
from django.conf.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.post_list, name="post_list"),
    re_path(r'^(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    re_path(r'^new/', views.post_new, name="post_new"),
    re_path(r'^(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.main, name="main"),
    re_path(r'^blog/', include(('blog.urls', 'blog'), namespace='blog'))
]

blog/models.py
from django.db import models
from django.shortcuts import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"

blog/views.py
from django.shortcuts import render,get_object_or_404, redirect, HttpResponseRedirect ,reverse
from .models import Post
from .forms import PostForm


def post_list(request):
    posts = Post.objects.all()

    return render(request, 'blog/post_list.html', {
        'post_list': posts
    })


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    return render(request, 'blog/post_detail.html', {
        'post': post
    })


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('blog:post_list')

    else:
        form = PostForm()
    return render(request, 'blog/post_new.html', {
        'form': form
    })


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('blog:post_list')

    else:
        form = PostForm(instance=post)

    return render(request, 'blog/post_edit.html', {
        'form': form
    })

mysite/views.py
from django.shortcuts import render


def main(request):
    return render(request, 'main.html')

blog/templates/blog/post_detail.html
<h1>{{ post.title }}</h1>

<p>{{ post.content }}</p>

<button type="button"><a href="{% url 'blog:post_edit' post.pk %}">글 수정</a></button>

blog/templates/blog/post_edit.html
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="전송">
</form>

blog/templates/blog/post_list.html
{% for i in post_list %}
<ul>
    <li><a href="{% url 'blog:post_detail' i.pk %}">{{ i.title }}</a></li>
</ul>
{% endfor %}


<hr>
<button type="button"><a href="{% url 'blog:post_new' %}">글쓰기</a></button>

blog/templates/blog/post_new.html
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="전송">
</form>

mysite/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>